title: "Aditya Anand"
description: "Resume + Blog"
url: "https://yourusername.github.io"
baseurl: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: ["Gemfile", "Gemfile.lock", "README.md"]
